# Generated by Django 3.2.3 on 2021-05-29 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumer',
            name='report',
            field=models.ImageField(upload_to='reports'),
        ),
        migrations.AlterField(
            model_name='consumer',
            name='severity',
            field=models.CharField(choices=[('Mi', 'Mild'), ('Mo', 'Moderate'), ('C', 'Critical')], default='Mi', max_length=50),
        ),
    ]
