# Generated by Django 3.2.3 on 2021-05-29 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0002_auto_20210529_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumer',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='consumer',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='consumer',
            name='report',
            field=models.ImageField(blank=True, null=True, upload_to='reports'),
        ),
    ]
