# Generated by Django 3.2.3 on 2021-05-29 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0003_auto_20210529_1704'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='bed', max_length=100)),
                ('count', models.IntegerField(default=0)),
                ('pending', models.BooleanField(default=False)),
                ('completed', models.DateField()),
                ('consumer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='consumer.consumer')),
            ],
        ),
    ]
