# Generated by Django 3.2.3 on 2021-05-29 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0006_auto_20210529_2154'),
        ('consumer', '0007_alter_consumer_phone'),
    ]

    operations = [
    ]
