# Generated by Django 3.2.3 on 2021-05-29 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0005_alter_resource_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='provider',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
