# Generated by Django 3.2.3 on 2021-05-28 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('startingTime', models.CharField(max_length=10)),
                ('endingTime', models.CharField(max_length=10)),
                ('homeDelivery', models.BooleanField(default=True)),
                ('callDuration', models.CharField(max_length=10)),
                ('available', models.BooleanField(default=True)),
                ('bed', models.IntegerField(default=0)),
                ('oxygenCylinder', models.IntegerField(default=0)),
                ('oxygenCylinderToolkit', models.IntegerField(default=0)),
                ('homeIsolationKit', models.IntegerField(default=0)),
            ],
        ),
    ]
