# Generated by Django 3.2.3 on 2021-05-29 07:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(default=None, max_length=100, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='provider',
            old_name='homeDelivery',
            new_name='deliver',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='available',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='bed',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='callDuration',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='endingTime',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='homeIsolationKit',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='oxygenCylinder',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='oxygenCylinderToolkit',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='startingTime',
        ),
        migrations.AddField(
            model_name='provider',
            name='dob',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='provider',
            name='pincode',
            field=models.IntegerField(null=True),
        ),
    ]
