# Generated by Django 3.2.3 on 2021-05-29 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0002_auto_20210529_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='type',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
