# Generated by Django 3.2.3 on 2021-05-29 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0003_alter_resource_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='name',
        ),
        migrations.AddField(
            model_name='resource',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resource',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='provider.provider'),
        ),
    ]
